export const TRENDING_ARTICLE_LIST_REQUEST = 'TRENDING_ARTICLE_LIST_REQUEST'
export const TRENDING_ARTICLE_LIST_SUCCESS = 'TRENDING_ARTICLE_LIST_SUCCESS'
export const TRENDING_ARTICLE_LIST_FAIL = 'TRENDING_ARTICLE_LIST_FAIL'

export const LATEST_ARTICLE_LIST_REQUEST = 'LATEST_ARTICLE_LIST_REQUEST'
export const LATEST_ARTICLE_LIST_SUCCESS = 'LATEST_ARTICLE_LIST_SUCCESS'
export const LATEST_ARTICLE_LIST_FAIL = 'LATEST_ARTICLE_LIST_FAIL'

export const ARTICLE_LIST_REQUEST = 'LATEST_ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_SUCCESS = 'LATEST_ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAIL = 'LATEST_ARTICLE_LIST_FAIL'

export const ARTICLE_DETAILS_REQUEST = 'LATEST_ARTICLE_DETAILS_REQUEST'
export const ARTICLE_DETAILS_SUCCESS = 'LATEST_ARTICLE_DETAILS_SUCCESS'
export const ARTICLE_DETAILS_FAIL = 'LATEST_ARTICLE_DETAILS_FAIL'